######################################################################
##
## Filename: multu_tb.udo
## Created on: Wed Jul 20 11:12:26 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
