######################################################################
##
## Filename: cc_tb.udo
## Created on: Thu Jul 21 17:10:09 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
