######################################################################
##
## Filename: mux2c1.udo
## Created on: Thu Jul 21 0:50:42 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
