######################################################################
##
## Filename: sccu_dataflow.udo
## Created on: Wed May 11 20:54:28 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
