######################################################################
##
## Filename: pc_reg.udo
## Created on: Wed May 11 17:40:40 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
