######################################################################
##
## Filename: sccpu_dataflow.udo
## Created on: Fri May 06 10:45:13 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
